language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "lts/erbium"
  - "lts/*"
  - "node"
notifications:
  email:
    recipients:
      - video-dev@ted.com
    on_success: change
    on_failure: always
